### ISSUE TITLE
Formulareditor: Controls können nicht gelöscht werden.

### ISSUE THREAD

**Issue by Eymux** [WollMux/formbox#66]
Wenn ich auf das Kreuz zum Löschen eines FormControls drücke, bekomme ich eine GeneralException.
Das Control wird nicht gelöscht.

ERROR GeneralException: GeneralException
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      code: "GeneralException",
      debugInfo: { },
      innerError: null,
      message: "GeneralException",
      name: "OfficeExtension.Error",
      stack: "GeneralException: GeneralException
   at Anonymous function (https://localhost:4200/assets/officejs/word-win32-16.01.js:21:223161)
   at ai (https://localhost:4200/assets/officejs/word-win32-16.01.js:21:268286)
   at ft (https://localhost:4200/assets/officejs/word-win32-16.01.js:21:268373)
   at d (https://localhost:4200/assets/officejs/word-win32-16.01.js:21:268193)
   at c (https://localhost:4200/assets/officejs/word-win32-16.01.js:21:266889)",
      Symbol()_j.5lrg8yesy8k: undefined,
      Symbol(asyncIterator)_g.5lrg8yesy8k: undefined,
      Symbol(observable)_i.5lrg8yesy8k: undefined,
      Symbol(rxSubscriber)_h.5lrg8yesy8k: undefined,
      traceMessages: [ ]
   }

**Comment by sikelerd** [comment]
Das Löschen funktioniert nicht, da die Propterty `style` des ContentControls auf einen nicht verfügbaren Wert gesetzt wird. Dies ist mit den Änderungen für SLVs hereingekommen.
`cc.style = 'Normal';` funktioniert nicht
`cc.styleBuiltIn = 'Normal';` funktioniert
Hier gibt es aber einen semantischen Unterschied. Welches Verhalten brauchen wir für die SLVs?
